name: Playwright Tests
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
jobs:
  playwright-test-job:
    timeout-minutes: 60
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Set release name
      run: |
        REL_NAME=${GITHUB_SHA::7}-execution-job
        echo "REL_NAME=$REL_NAME" >> $GITHUB_ENV

    - name: Run Playwright tests
      run: sudo helm install $REL_NAME ./helm-playwright -f ./helm-playwright/values/ci.yaml

    - name: Wait Playwright Job Finish
      run: |
  
        for i in {1..36}; do
            SUCCEEDED=$(sudo kubectl get job $REL_NAME -n default -o jsonpath='{.status.succeeded}' 2>/dev/null)
            FAILED=$(sudo kubectl get job $REL_NAME -n default -o jsonpath='{.status.failed}' 2>/dev/null)

            if [ "$SUCCEEDED" == "1" ]; then
                echo "Job Success"
                exit 0
            fi

            if [ "$FAILED" != "" ] && [ "$FAILED" != "0" ]; then
                echo "Job Failed"
                sudo kubectl logs job/$REL_NAME --all-containers=true
                exit 1
            fi

            echo "Waiting job status..."
            sleep 5
        done

        echo "Timeout waiting job"
        exit 1
      continue-on-error: true

    - name: Verify Job Status
      run: |
        FAILED=$(sudo kubectl get job $REL_NAME -o jsonpath='{.status.failed}')
        if [ "$FAILED" != "0" ]; then
          exit 1
        fi
    - name: Cleanup Helm Release
      run : |
        sudo helm uninstall $REL_NAME

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
